module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testTimeout: 30000,
  setupFiles: ['<rootDir>/tests/env-setup.ts'],
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  moduleNameMapper: {
    '^@config/(.*)$': '<rootDir>/src/config/$1',
    '^@controllers/(.*)$': '<rootDir>/src/controllers/$1',
    '^@middlewares/(.*)$': '<rootDir>/src/middlewares/$1',
    '^@routes/(.*)$': '<rootDir>/src/routes/$1',
    '^@schema/(.*)$': '<rootDir>/src/schema/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@types/(.*)$': '<rootDir>/src/types/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@workers/(.*)$': '<rootDir>/src/workers/$1',
    '^@db/(.*)$': '<rootDir>/src/db/$1',
    '^@generated/(.*)$': '<rootDir>/generated/$1',
    '^db$': '<rootDir>/src/db',
    '^types/(.*)$': '<rootDir>/src/types/$1',
    '^app$': '<rootDir>/src/app',
    '^services/(.*)$': '<rootDir>/src/services/$1',
    '^schema/(.*)$': '<rootDir>/src/schema/$1',
    '^middlewares/(.*)$': '<rootDir>/src/middlewares/$1',
    '^controllers/(.*)$': '<rootDir>/src/controllers/$1',
    '^utils/(.*)$': '<rootDir>/src/utils/$1',
    '^config/(.*)$': '<rootDir>/src/config/$1',
  },
};
